master_language: en
languages:
    - en
    - es
    - ca
    - fr
    - de
    - it
    - fi
    - eu
    - gl
    - eo
    - nl
    - sr
    - zh_CN
paths:
    - src/Elcodi/*/*/Resources/translations