services:
#    best365.example:
#        class: Best365Bundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    best365.manager.membership:
        class: Best365Bundle\Manager\MembershipManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.customer:
        class: Best365Bundle\Manager\Best365CustomerManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.purchasable:
        class: Best365Bundle\Manager\PurchasableManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@elcodi.repository.purchasable'
            - '@elcodi.wrapper.customer'
            - '@best365.manager.membership'

    best365.manager.address:
        class: Best365Bundle\Manager\Best365AddressManager

    best365.manager.order:
        class: Best365Bundle\Manager\Best365OrderManager
        arguments:
            - "@paymentsuite.freepayment.method_factory"
            - "@paymentsuite.bridge"
            - "@paymentsuite.event_dispatcher"
            - '@elcodi.object_manager.order'
            - '@elcodi.wrapper.customer'
            - '@elcodi.wrapper.shipping_methods'
            - "@elcodi.converter.currency"
            - '@best365.manager.customer'
            - '@best365.manager.purchasable'
            - '@best365.manager.payment'
            - '@best365.manager.cart'
            - '@doctrine.orm.entity_manager'

    best365.manager.payment:
        class: Best365Bundle\Manager\Best365PaymentManager
        arguments:
            - "%epayment_merchant_id%"
            - "%epayment_merchant_key%"
            - "%epayment_qrcode_url%"
            - "%paymark_username%"
            - "%paymark_password%"
            - "%paymark_account_id%"
            - "%paymark_request_url%"
            - "@router"
            - "@elcodi.wrapper.currency"
            - "@elcodi.converter.currency"
            - "@elcodi.repository.currency"
            - '@doctrine.orm.entity_manager'

    best365.manager.event:
        class: Best365Bundle\Manager\EventManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.promotion:
        class: Best365Bundle\Manager\PromotionManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.trends:
        class: Best365Bundle\Manager\TrendsManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.cart:
        class: Best365Bundle\Manager\Best365CartManager
        arguments:
            - '@elcodi.manager.cart'
            - '@elcodi.wrapper.cart'
            - '@elcodi.factory.cart'
            - '@elcodi.event_dispatcher.cart'