services:
#    best365.example:
#        class: Best365Bundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    best365.manager.membership:
        class: Best365Bundle\Manager\MembershipManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.customer:
        class: Best365Bundle\Manager\Best365CustomerManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.purchasable:
        class: Best365Bundle\Manager\PurchasableManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@elcodi.repository.purchasable'
            - '@elcodi.wrapper.customer'
            - '@elcodi.converter.currency'
            - "@elcodi.repository.currency"
            - "@elcodi.repository.manufacturer"
            - "@elcodi.repository.entity_translation"
            - "@best365.manager.bestselling"

    best365.manager.address:
        class: Best365Bundle\Manager\Best365AddressManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@elcodi.repository.address"
            - "@security.token_storage"
            - "@elcodi.wrapper.cart"
            - "@elcodi.object_manager.cart"

    best365.manager.order:
        class: Best365Bundle\Manager\Best365OrderManager
        arguments:
            - "@paymentsuite.freepayment.method_factory"
            - "@paymentsuite.bridge"
            - "@paymentsuite.event_dispatcher"
            - '@elcodi.object_manager.order'
            - '@elcodi.repository.order'
            - '@elcodi.wrapper.shipping_methods'
            - "@elcodi.converter.currency"
            - "@elcodi.wrapper.currency"
            - '@best365.manager.purchasable'
            - '@best365.manager.payment'
            - '@best365.manager.cart'
            - "@best365.manager.customer"
            - "@elcodi.order_payment_states_machine_manager"
            - '@doctrine.orm.entity_manager'
            - "@router"
            - "@elcodi.order_payment_states_machine_manager"

    best365.manager.payment:
        class: Best365Bundle\Manager\Best365PaymentManager
        arguments:
            - "%epayment_merchant_id%"
            - "%epayment_merchant_key%"
            - "%epayment_qrcode_url%"
            - "%paymark_username%"
            - "%paymark_password%"
            - "%paymark_account_id%"
            - "%paymark_request_url%"
            - "%poli_crt%"
            - "%poli_merchant_code%"
            - "%poli_auth_code%"
            - "%poli_initiate_api%"
            - "%poli_transaction_api%"
            - "@router"
            - "@elcodi.converter.currency"
            - "@elcodi.repository.currency"
            - '@doctrine.orm.entity_manager'

    best365.manager.event:
        class: Best365Bundle\Manager\EventManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.promotion:
        class: Best365Bundle\Manager\PromotionManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.trends:
        class: Best365Bundle\Manager\TrendsManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.cart:
        class: Best365Bundle\Manager\Best365CartManager
        arguments:
            - '@elcodi.manager.cart'
            - '@elcodi.factory.cart'
            - '@elcodi.event_dispatcher.cart'
            - '@best365.manager.purchasable'
            - "@elcodi.converter.currency"

    best365.manager.category:
        class: Best365Bundle\Manager\Best365CategoryManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@elcodi_store.store_category_tree'
            - '@elcodi.repository.category'

    best365.manager.bestselling:
        class: Best365Bundle\Manager\Best365BestsellingManager
        arguments:
            - '@doctrine.orm.entity_manager'

    best365.manager.shipping:
        class: Best365Bundle\Manager\Best365ShippingManager

    best365.manager.store:
        class: Best365Bundle\Manager\Best365StoreManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@elcodi.repository.store'
            - '@elcodi.repository.address'

    best365.manager.manufacturer:
        class: Best365Bundle\Manager\Best365ManufacturerManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@elcodi.repository.manufacturer'