services:

    #
    # Services
    #
    elcodi.manager.currency:
        class: Elcodi\Component\Currency\Services\CurrencyManager
        arguments:
            - '@elcodi.repository.currency'
            - '@elcodi.repository.currency_exchange_rate'
            - %elcodi.default_currency%