<?php

namespace Best365Bundle\Repository;

/**
 * AddressImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressImageRepository extends \Doctrine\ORM\EntityRepository
{
}
