<?php

namespace Best365Bundle\Repository;

/**
 * BestsellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestsellingRepository extends \Doctrine\ORM\EntityRepository
{
}
