<?php

namespace Best365Bundle\Repository;

/**
 * CategoryExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryExtRepository extends \Doctrine\ORM\EntityRepository
{
}
