<?php

namespace Best365Bundle\Repository;

/**
 * CustomerExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerExtRepository extends \Doctrine\ORM\EntityRepository
{
}
