<?php

namespace Best365Bundle\Repository;

/**
 * CustomerMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerMembershipRepository extends \Doctrine\ORM\EntityRepository
{
}
