<?php

namespace Best365Bundle\Repository;

/**
 * EpaymentOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpaymentOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
