<?php

namespace Best365Bundle\Repository;

/**
 * OrderExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderExtRepository extends \Doctrine\ORM\EntityRepository
{
}
