<?php

namespace Best365Bundle\Repository;

/**
 * PaymentGatewayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentGatewayRepository extends \Doctrine\ORM\EntityRepository
{
}
