<?php

namespace Best365Bundle\Repository;

/**
 * PurchasableExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasableExtRepository extends \Doctrine\ORM\EntityRepository
{
}
