<?php

namespace Best365Bundle\Repository;

/**
 * PurchasablePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasablePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
