<?php

namespace Best365Bundle\Repository;

/**
 * PurchasableTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasableTagRepository extends \Doctrine\ORM\EntityRepository
{
}
