<?php

namespace Best365Bundle\Repository;

/**
 * TrendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrendsRepository extends \Doctrine\ORM\EntityRepository
{
}
