Best365Bundle\Entity\Bestselling:
    type: entity
    table: bestselling
    repositoryClass: Best365Bundle\Repository\BestsellingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pid:
            type: integer
    lifecycleCallbacks: {  }
