Best365Bundle\Entity\EpaymentOrder:
    type: entity
    table: epayment_order
    repositoryClass: Best365Bundle\Repository\EpaymentOrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tradeNo:
            type: string
            length: 255
            column: trade_no
        params:
            type: text
    lifecycleCallbacks: {  }
