Best365Bundle\Entity\Event:
    type: entity
    table: event
    repositoryClass: Best365Bundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        link:
            type: string
            length: 255
        enabled:
            type: integer
    lifecycleCallbacks: {  }
