Best365Bundle\Entity\PurchasableExt:
    type: entity
    table: purchasable_ext
    repositoryClass: Best365Bundle\Repository\PurchasableExtRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        purchasableId:
            type: integer
            column: purchasable_id
        tag:
            type: string
            length: 255
        barcode:
            type: string
            length: 255
    lifecycleCallbacks: {  }
